services:
  postgresql:
    image: postgres:latest
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  go-app:
    image: pib21/go-app-build:v1
    ports:
      - "8000:8000"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: postgresql
      DB_PORT: ${DB_PORT}
      DB_SSLMODE: ${DB_SSLMODE}
      DB_TIMEZONE: ${DB_TIMEZONE}
      GMAIL: ${GMAIL}
      GPASS: ${GPASS}
      DOMAIN: ${DOMAIN}
    depends_on:
      postgresql:
        condition: service_healthy
    restart: unless-stopped
    env_file:
      - .env

volumes:
  postgres_data:
